# check if tests succeed
sudo: required
language: python
python:
  - "3.6"

before_install:
  # We put all environment variables with TRAVIS_ in the beginning in a file to read it later (e.g., for github token)
  - printenv | grep -E '^TRAVIS_' > .env
  - sudo apt-get update
  - sudo apt-get install -y build-essential wget git
  - sudo apt-get install -y python3-pip python3-cffi
  - pip install -U pip setuptools
  - pip install Sphinx
  - pip install sphinx_rtd_theme
  - pip install ghp_import

install:
  - python setup.py install

script:
  - python setup.py test

after_success:
  - make deploy

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "mailingSHARK_plugin.tar"
  skip_cleanup: true
  on:
    repo: smartshark/mailingSHARK
    tags: true